controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

api.controllers:
    resource: '../src/Controller/Api'
    type: attribute
    prefix: /api

app.security.login:
    path: /token
